[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
parameterized_test = "0.1.0"
regex = "1.7.0"
once_cell = "1.16.0"
advent-of-code-helpers = { git = "https://github.com/stevenliebregt/advent-of-code-helpers" }